---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - jonasasx.io
  resources:
  - secretors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jonasasx.io
  resources:
  - secretors/finalizers
  verbs:
  - update
- apiGroups:
  - jonasasx.io
  resources:
  - secretors/status
  verbs:
  - get
  - patch
  - update
