# permissions for end users to view secretors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretor-viewer-role
rules:
- apiGroups:
  - io.jonasasx.io.jonasasx
  resources:
  - secretors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - io.jonasasx.io.jonasasx
  resources:
  - secretors/status
  verbs:
  - get
