# permissions for end users to edit secretors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretor-editor-role
rules:
- apiGroups:
  - jonasasx.io
  resources:
  - secretors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jonasasx.io
  resources:
  - secretors/status
  verbs:
  - get
