---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "secretor.fullname" . }}
rules:
  - apiGroups:
      - jonasasx.io
    resources:
      - secretors
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - jonasasx.io
    resources:
      - secretors/finalizers
    verbs:
      - update
  - apiGroups:
      - jonasasx.io
    resources:
      - secretors/status
    verbs:
      - get
      - patch
      - update
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - create
      - update
      - patch
      - list
      - watch
  - apiGroups: [""]
    resources:
      - events
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "secretor.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "secretor.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "secretor.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
